#!/usr/bin/env python3

# The following Python script prints the subjects that a specified student 
# studied in a given term. 
# There is no need to check whether the student was enrolled in the given term; 
# simply print that they studied no courses in that term.

import sys
import psycopg2

if len(sys.argv) != 3:
  print("Usage: ./courses-studied studentID term")
  exit(1)

studentID = sys.argv[1]
term = sys.argv[2]
conn = None

query = '''
select s.code, s.name
from Subjects s
  join Courses c on (s.id = c.subject)
  join Course_enrolments e on (e.course = c.id)
  join Terms t on (t.id = c.term)
  join Students d on (d.id = e.student)
where d.id = %s and t.code = %s
order by s.code, s.name
'''

try:
  conn = psycopg2.connect("dbname=uni")
  cur = conn.cursor()

  cur.execute(query, [studentID, term])

  res = cur.fetchall()

  if len(res) == 0:
    print("No such student")
  else:
    for code, name in res:
      print(f"{code} {name}")


except psycopg2.Error as err:
  print("database error: ", err)

finally:
  if conn is not None:
    conn.close()
