#!/usr/bin/env python3

# Method 1: Widen the scope of `conn` variable
# Method 2: Have a flag variable that checks if `conn` is initialised

import sys
import psycopg2

if len(sys.argv) < 2:
  print("Usage: opendb DBname")
  exit(1)

db = sys.argv[1]
conn = None # Method 1

try:
  conn = psycopg2.connect(f"dbname={db}")
  print(conn)
  cur = conn.cursor()

except psycopg2.Error as err:
  print("database error: ", err)
  flag = True # Method 2

finally:
  if not flag and conn is not None: # Method 2
    conn.close()
  print("finished with the database")